### ISSUE TITLE
createPool throws RangeError when trying to decode assetData buffer

### ISSUE THREAD

**Issue by paged1** [Bonfida/bonfida-bot#2]
I'm having trouble creating a pool using your documentation, specifically the example found [here](https://bonfida.github.io/bonfida-bot-docs/#creating-a-pool)

```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:81:11)
    at Buffer.readUInt32LE (internal/buffer.js:217:5)
    at Buffer.readUIntLE (internal/buffer.js:175:17)
    at UInt.decode (/Users/dirksmac/dev/reckoning/bonfida/node_modules/buffer-layout/lib/Layout.js:572:14)
    at Structure.decode (/Users/dirksmac/dev/reckoning/bonfida/node_modules/buffer-layout/lib/Layout.js:1238:32)
    at createPool (/Users/dirksmac/dev/reckoning/bonfida/node_modules/bonfida-bot/dist/main.js:103:77)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async pool (file:///Users/dirksmac/dev/reckoning/bonfida/index.mjs:49:46) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```

This is the .mjs file i'm using to try to create the pool: (there are a few changes i made from the example in the documentation because of syntax errors)

```
import { Connection, Account, PublicKey } from '@solana/web3.js';
import { createPool } from 'bonfida-bot';
import { signAndSendTransactionInstructions, Numberu64, Numberu16 } from 'bonfida-bot';
import { BONFIDABOT_PROGRAM_ID, SERUM_PROGRAM_ID, ENDPOINTS } from 'bonfida-bot';

const connection = new Connection(ENDPOINTS.mainnet);

const sourceOwnerAccount = new Account(["<MY PRIVATE KEY ARRAY>"]);
const signalProviderAccount = new Account(["<MY PRIVATE KEY ARRAY AGAIN>"]);

// The payer account will pay for the fees involved with the transaction.
// For the sake of simplicity, we choose the source owner.
const payerAccount = sourceOwnerAccount;

// Creating a pool means making the initial deposit.
// Any number of assets can be added. For each asset, the public key of the payer token account should be provided.
// The deposit amounts are also given
const sourceAssetKeys = [
    new PublicKey('<MY PUBLIC KEY>'),
]
const deposit_amounts = [1];

// Maximum number of assets that can be held by the pool at any given time.
// A higher number means more flexibility but increases the initial pool account allocation fee.
const maxNumberOfAsset = 10;

// It is necessary for the purpose of security to hardcode all Serum markets that will be usable by the pool.
// It is advised to put here as many trusted markets with enough liquidity as required.
const allowedMarkets = ['A8YFbxQYFVqKZaoYJLLUVcQiWP7G2MeEgW5wsAQgMvFw']; // i used the BTC/USDC address

// Interval of time in seconds between two fee collections. This must be greater or equal to a week.
// @ts-ignore
const feeCollectionPeriod = new Numberu64(604800);

// Total ratio of pool to be collected as fees at an interval defined by feeCollectionPeriod
// @ts-ignore
const feeRatio = 0.001;

const pool = async () => {

    // Create pool
    try {
        let [poolSeed, createInstructions] = await createPool(
            connection,
            sourceOwnerAccount.publicKey,
            sourceAssetKeys,
            signalProviderAccount.publicKey,
            deposit_amounts,
            maxNumberOfAsset,
            allowedMarkets,
            payerAccount.publicKey,
            // @ts-ignore
            feeCollectionPeriod,
            // @ts-ignore
            feeRatio
        )
    
        await signAndSendTransactionInstructions(
            connection,
            [sourceOwnerAccount], // The owner of the source asset accounts must sign this transaction.
            payerAccount,
            createInstructions
        );
        console.log("Created Pool");
    }
    catch (err) {
        console.log(err);
    }

}

pool();

```

**Comment by dr497** [comment]
Hey @paged1 ! Thanks for your message.

There are few things to change in your code to make it work:

- `sourceAssetKeys` is an array that contains the addresses of the `sourceOwnerAccount ` for BTC and USDC

- `deposit_amounts` needs to contain the amount for all the tokens deposited i.e BTC and USDC. You can change it to `[0, 0]`

- ` allowedMarkets` is a an array of `PublicKey`. You can change it to:

`const allowedMarkets = [
  new PublicKey("A8YFbxQYFVqKZaoYJLLUVcQiWP7G2MeEgW5wsAQgMvFw"),
];`

Let me know if you still encounter an error.

**Comment by Lcchy** [comment]
Hi @paged1, thanks a lot for your input. 

I updated the doc and all the examples are fully functional now, please let us know if any other questions or problems arise!

**Comment by ogreckoner20** [comment]
@dr497 when you say sourceOwnerAccount do you mean to say the address that currently **has** the BTC and USDC or the contract address **of** the BTC and USDC on solana?

**Comment by paged1** [comment]
@dr497 After making changes i'm now getting a similar error, my initializations now look like this:

```
import { Connection, Account, PublicKey } from '@solana/web3.js';
import { createPool } from 'bonfida-bot';
import { signAndSendTransactionInstructions, Numberu64, Numberu16 } from 'bonfida-bot';
import { BONFIDABOT_PROGRAM_ID, SERUM_PROGRAM_ID, ENDPOINTS } from 'bonfida-bot';

const connection = new Connection(ENDPOINTS.mainnet);

const sourceOwnerAccount = new Account(["<PRIVATE KEYS>"]);
const signalProviderAccount = new Account(["<PRIVATE KEYS>"]);

const payerAccount = sourceOwnerAccount;

const sourceAssetKeys = [
    new PublicKey('9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E'),
    new PublicKey('BXXkv6z8ykpG1yuvUDPgh732wzVHB69RnB9YgSYh3itW')
]
const deposit_amounts = [0,0];
const maxNumberOfAsset = 10;

const allowedMarkets = [new PublicKey('A8YFbxQYFVqKZaoYJLLUVcQiWP7G2MeEgW5wsAQgMvFw')];

const feeCollectionPeriod = new Numberu64(604800);

const feeRatio = 0.001;
```
Where i'm getting sourceAssetKeys from [here (BTC)](https://explorer.solana.com/address/9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E) and [here (USDC)](https://explorer.solana.com/address/BXXkv6z8ykpG1yuvUDPgh732wzVHB69RnB9YgSYh3itW)
If these are not the correct inputs for sourceAssetKeys could you elaborate on where to find them?

here is the output:
```
RangeError [ERR_OUT_OF_RANGE]: The value of “offset” is out of range. It must be >= 0 and <= 81. Received 108
  at boundsError (internal/buffer.js:83:9)
  at Buffer.readUInt8 (internal/buffer.js:249:5)
  at Buffer.readUIntLE (internal/buffer.js:179:17)
  at UInt.decode (/Users/dirksmac/dev/reckoning/bonfida/node_modules/buffer-layout/lib/Layout.js:572:14)
  at Structure.decode (/Users/dirksmac/dev/reckoning/bonfida/node_modules/buffer-layout/lib/Layout.js:1238:32)
  at createPool (/Users/dirksmac/dev/reckoning/bonfida/node_modules/bonfida-bot/dist/main.js:103:77)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async pool (file:///Users/dirksmac/dev/reckoning/bonfida/index.mjs:46:46) {
 code: ‘ERR_OUT_OF_RANGE’
}
```

**Comment by Lcchy** [comment]
@ogreckoner20 The sourceOwnerAccount is the owner of the sourceAssetKeys in the token way that is (ie the sourceAssetKeys are the token accounts associated to the sourceOwnerAccount). It means that in order to find them you can go to the explorer on your own address (the sourceOwnerAccount) and look at the token holding. For this [account](https://explorer.solana.com/address/CYK7sXKURRfPyXojLiZwU1y9AAT5RJoJ3ac3RWJutTKi) it would be `2qCLHQRJnN3SzJgfRjYpEvUn55K3bCVMrFXd99M26dye` for FIDA and `8WkPdevD8JY9z5FggHTc9pxftkTYBPBj3ayBn2x9bWJ4` for USDC (for example).

@paged1 The deposit_amounts are better set to something non zero like in the docs (ie 1000000 for 1 USDC, don't forget the precision), or else you won't be able to deposit into the pool later on, as the value of a pooltoken wouldn't be mathematically defined.
For your buffer error it seems like the private key you provided for the sourceOwnerAccount or signalProviderAccount was not of the correct length.
Here is an example of a (devnet) private key:
`[114,240,0,110,11,115,115,128,85,208,169,15,114,229,161,53,148,113,226,225,158,132,4,167,156,50,26,199,109,251,84,183,216,239,228,135,91,208,199,109,31,199,176,100,86,226,62,111,58,104,138,110,0,96,113,186,108,176,52,143,226,195,219,252]`
You can access it with `cat id.json` where id.json is the key file.

---

IF your wallet is on sollet, you can get the private key or directly instantiate the account with one of those two functions:
```
// For accounts imported from Sollet.io
export const getDerivedSeed = (seed: Buffer): Uint8Array => {
  const derivedSeed = bip32.fromSeed(seed).derivePath(`m/501'/0'/0/0`)
    .privateKey;
  return nacl.sign.keyPair.fromSeed(derivedSeed).secretKey;
};

export const getAccountFromSeed = (seed: Buffer): Account => {
  const derivedSeed = bip32.fromSeed(seed).derivePath(`m/501'/0'/0/0`)
    .privateKey;
  return new Account(nacl.sign.keyPair.fromSeed(derivedSeed).secretKey);
};
```
They can also be imported from `'bonfida-bot'` and have to be called on the sollet seed.
That seed is a bit tricky to get to, you have to go on the sollet page and (on Firefox at least):
- go to the storage tab
- open the LocalStorage
- copy the seed which should be located just after the mnemonic

It may be easier to use a cli solana wallet in order to extract the private key so you could just transfer the funds from the sollet wallet.  

Let us know if you have any issues!

**Comment by paged1** [comment]
@Lcchy My private key is an array of 64 integers like the example you've given so i think it checks out.

I've changed my deposit_amounts to `[1000000,1000000]` based on the return value 6 from the `decimalsFromMint` function in the doc

I did find the proper inputs for sourceAssetKeys from my [token holdings table](https://explorer.solana.com/address/AJt7ptGVxdmUkf27ca95oYi19PAuvAbeCHXaotSMh4tF/tokens?display=detail) when I selected **Detailed** instead of **Summary**. But unfortunately now i'm getting a new error, this time from the call to `signAndSendTransactionInstructions`.

`createPool` completes execution without error but then the following output is printed:

```
Transaction simulation failed: Error processing Instruction 4: custom program error: 0x1 
    Program 63xyXHpA6EVF69kRmEbXAr8aBEkhgpaNUSRoTQyi5Rwr invoke [1]
    Program log: Entrypoint
    Program log: Beginning processing
    Program log: Instruction unpacked
    Program log: Instruction: Init
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: InitializeMint
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2834 of 179702 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program 63xyXHpA6EVF69kRmEbXAr8aBEkhgpaNUSRoTQyi5Rwr consumed 23764 of 200000 compute units
    Program 63xyXHpA6EVF69kRmEbXAr8aBEkhgpaNUSRoTQyi5Rwr success
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]
    Program log: Transfer 2039280 lamports to the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Allocate space for the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Assign the associated token account to the SPL Token program
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Initialize the associated token account
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: InitializeAccount
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3920 of 179575 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 24994 of 200000 compute units
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]
    Program log: Transfer 2039280 lamports to the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Allocate space for the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Assign the associated token account to the SPL Token program
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Initialize the associated token account
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: InitializeAccount
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3922 of 164293 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 40310 of 200000 compute units
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]
    Program log: Transfer 2039280 lamports to the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Allocate space for the associated token account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Assign the associated token account to the SPL Token program
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Initialize the associated token account
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: InitializeAccount
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3959 of 176938 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 27702 of 200000 compute units
    Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success
    Program 63xyXHpA6EVF69kRmEbXAr8aBEkhgpaNUSRoTQyi5Rwr invoke [1]
    Program log: Entrypoint
    Program log: Beginning processing
    Program log: Instruction unpacked
    Program log: Instruction: Create Pool
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: Transfer
    Program log: Error: insufficient funds
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2662 of 175772 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: custom program error: 0x1
    Program 63xyXHpA6EVF69kRmEbXAr8aBEkhgpaNUSRoTQyi5Rwr consumed 26890 of 200000 compute units
    Program 63xyXHpA6EVF69kRmEbXAr8aBEkhgpaNUSRoTQyi5Rwr failed: custom program error: 0x1
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x1
    at Connection.sendEncodedTransaction (/Users/dirksmac/dev/reckoning/bonfida/node_modules/@solana/web3.js/lib/index.cjs.js:3556:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Connection.sendRawTransaction (/Users/dirksmac/dev/reckoning/bonfida/node_modules/@solana/web3.js/lib/index.cjs.js:3517:20)
    at async Connection.sendTransaction (/Users/dirksmac/dev/reckoning/bonfida/node_modules/@solana/web3.js/lib/index.cjs.js:3507:12)
    at async signAndSendTransactionInstructions (/Users/dirksmac/dev/reckoning/bonfida/node_modules/bonfida-bot/dist/utils.js:197:12)
    at async pool (file:///Users/dirksmac/dev/reckoning/bonfida/index.mjs:79:9)
```

The message that stands out is insufficient funds but this is only supposed to be a simulated transaction?

**Comment by Lcchy** [comment]
@paged1 Oh cool, this seems better already. When a node of the solana network executes the transaction you sent, it firsts simulates how it would go, and in your case the simulation showed that your `sourceAssetAccounts` do not hold enough tokens for the transfer of `deposit_amounts` to be successful. 
Your BTC account seems to hold 0.000169 BTC, which would translate to a deposit_amount of 169, if you specified 1000000 in `deposit_amount` for BTC, it means you tried to deposit 1 BTC which does not seem to be available.

**Comment by paged1** [comment]
Changing to `deposit_amounts = [100, 1000000]` fixed that error. No more issues with createPool, thanks @Lcchy
